### ISSUE TITLE
Flush handler conflict while using multiple roles

### ISSUE THREAD

**Issue by flotho** [robertdebock/ansible-collection-roles#6]
Hi,

I'm running mutiple of your roles in a playbook :
```
.../..
  roles:
    - role: robertdebock.roles.locale
      vars:
        locale_timezone: "{{ ntp_timezone }}"
    - role: robertdebock.roles.openssh
    - role: robertdebock.roles.git
    - role: robertdebock.roles.logrotate
    - role: robertdebock.roles.investigate
```

My host is a rocky linux 9 uptodate.
The first time I run this sequence, the flush handler in openssh is triggering an event causing an issue on the locale :
```
TASK [robertdebock.roles.openssh : Flush handlers] *********************************************************************************************
task path: /home/florent.thomas/DEV/Projets_Infra/all-ansible-tools/ansible_collections/robertdebock/roles/roles/openssh/tasks/main.yml:55
[WARNING]: flush_handlers task does not support when conditional

RUNNING HANDLER [robertdebock.roles.locale : Localectl set-locale] *****************************************************************************
task path: /home/florent.thomas/DEV/Projets_Infra/all-ansible-tools/ansible_collections/robertdebock/roles/roles/locale/handlers/main.yml:4
fatal: [sso.mind-and-go.net]: FAILED! => {"changed": true, "cmd": ["localectl", "set-locale", "LANG=fr_FR.utf8"], "delta": "0:00:00.037381", "end": "2022-12-22 21:54:25.241665", "msg": "non-zero return code", "rc": 1, "start": "2022-12-22 21:54:25.204284", "stderr": "Failed to issue method call: Locale fr_FR.utf8 not installed, refusing.", "stderr_lines": ["Failed to issue method call: Locale fr_FR.utf8 not installed, refusing."], "stdout": "", "stdout_lines": []}

RUNNING HANDLER [robertdebock.roles.openssh : Restart openssh] *********************************************************************************
task path: /home/florent.thomas/DEV/Projets_Infra/all-ansible-tools/ansible_collections/robertdebock/roles/roles/openssh/handlers/main.yml:4
META: ran handlers
```
Even if we have an issue there, y=the locale has correctly been set.

Moreover, running a second time the same sequence succeeded.

AFAICS, this part of the code https://github.com/robertdebock/ansible-collection-roles/blob/master/roles/openssh/tasks/main.yml#L56 is triggering this other part : https://github.com/robertdebock/ansible-collection-roles/blob/master/roles/locale/handlers/main.yml#L4

I don't know what to do
